baseURL = 'https://ficelle.netlify.app/'
languageCode = 'fr-fr'
defaultContentLanguage = 'fr'
title = 'Ficelle'

enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[taxonomies]
  tag = "tags"
  category = "categories"
